name: draw keymap

on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - ".github/workflows/doc.yml"
      - "keymap_img/keymap_drawer.config.yaml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "boards/*/*/*.keymap"
      - "boards/*/*/*.dtsi"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      commit_message: "doc: update keymap image"           # commit message for the changes
      keymap_patterns: "boards/*/*/*.keymap"               # path to the keymaps to parse
      config_path: "keymap_img/keymap_drawer.config.yaml"  # config file, ignored if it does not exist
      output_folder: "keymap_img"                          # path to save produced SVG and keymap YAML files
      parse_args: "temper:'-c 10'"                         # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "temper:'-k chocofi -s default num nav fun'"   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"